name: sphia
description: Sphia - a Proxy Handling Intuitive Application
publish_to: 'none'

version: 0.7.7+8

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.1.2
  drift: ^2.11.0
  dropdown_search: ^5.0.6
  file_picker: ^6.1.1
  fixnum: ^1.1.0
  fl_chart: ^0.66.2
  get_it: ^7.4.0
  grpc: ^3.2.2
  http: ^1.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  launch_at_startup: ^0.2.2
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.0.15
  protobuf: ^3.0.0
  provider: ^6.0.5
  pub_semver: ^2.1.4
  qr_flutter: ^4.1.0
  quiver: ^3.2.1
  sqlite3_flutter_libs: ^0.5.0
  system_tray: ^2.0.3
  tuple: ^2.0.2
  updat: ^1.3.1
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.4
  drift_dev: ^2.11.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/sphia.db
    - assets/tray_color_off.ico
    - assets/tray_color_on.ico
    - assets/tray_no_color_off.png
    - assets/tray_no_color_on.png
    - assets/logo_about.png
    - assets/app_icon.ico
    - assets/app_icon.png

flutter_intl:
  enabled: true
  main_locale: en_US
  output_dir: lib/l10n/generated